runCDPipeline(application: env.APP_NAME,
              agent: "maven",
              compileCommands: "mvn package -DskipTests -Dfabric8.skip -e -B",
              testCommands: "",
              artifactDir: ".")
  