runCDPipeline(application: env.APP_NAME,
              agent: "maven",
              compileCommands: "mvn -s /home/jenkins/settings-newsan/settings.xml clean install -DskipTests",
              testCommands: "",
              artifactsDir: "./target")
  