apiVersion: v1
kind: Template
metadata:
  name: test-approval
objects:
parameters:
- description: Application Name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: ${APP_NAME}-prod