runCIPipeline(application: "test-approval",
              agent: "maven",
              compileCommands: "mvn clean install -DskipTests",
              testCommands: "",
              artifactDir: ".",
              approversGroup: "test-approval-approvers")
              