runCIPipelineQuay(application: "test-approval",
              project: "test-push-quay",
              agent: "maven",
              compileCommands: "mvn clean install -DskipTests",
              testCommands: "",
              artifactsDir: "./target",
              applicationTemplate: "./openshift/template.yaml")
              
