runCIPipeline(application: env.APP_NAME,
              agent: "maven",
              compileCommands: "mvn clean install -DskipTests",
              testCommands: "",
              artifactsDir: "./target")
              

              
